version: '3.9'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo_volume:/data/db

  server:
    build:
      dockerfile: development.dockerfile
      context: .
    env_file:
      - .env.compose
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - mongo
volumes:
  mongo_volume:
